# Generated by Django 3.1.7 on 2021-04-16 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinkapp', '0004_auto_20210414_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='photo',
        ),
    ]
