# Generated by Django 3.1.7 on 2021-04-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkapp', '0005_remove_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.FileField(default='~\\drinkapp\\HTMLTemplate\x07ssets\\images\\logo-icon.png', upload_to='uploads/'),
        ),
    ]
