# Generated by Django 3.1.7 on 2021-04-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkapp', '0006_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='~\\drinkapp\\HTMLTemplate\x07ssets\\images\\logo-icon.png', upload_to='static/uploads/'),
        ),
    ]
