# Generated by Django 3.1.7 on 2021-04-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkapp', '0007_auto_20210419_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='default', upload_to='gallery'),
        ),
    ]
